# Auto-generated by generate_cffi_defs.py – DO NOT EDIT
CDEF_SOURCE = '''\
typedef struct {
    int node_id;
    int delay_ms;
    float x;
    float y;
    int radius;
} NodeData;
typedef struct {
    int from_id;
    int to_id;
} EdgeData;
typedef struct {
    int nb_ants;
    int set_nb_nodes;
    int min_hops;
    int max_hops;
    int default_min_delay;
    int default_max_delay;
    int death_delay;
    int under_attack_id;
    _Bool attack_started;
    _Bool simulate_ddos;
    _Bool show_random_performance;
    _Bool show_brute_performance;
    double ranking_alpha;
    double ranking_beta;
    double ranking_gamma;
    float ant_alpha;
    float ant_beta;
    float ant_Q;
    float ant_evaporation;
} AppConfig;
typedef struct {
    int candidate_nodes[1024];
    int candidate_count;
    int current_L;
    int permutation[1024];
    int combination[1024];
    int at_first_permutation;
    int at_first_combination;
    int done;
} BruteForceState;
typedef struct {
    int *nodes;
    int node_count;
    int total_latency;
} AntNetPathInfo;
typedef struct {
    char __size[56];
} pthread_attr_t;
typedef struct {
    char __size[40];
} pthread_mutex_t;
typedef struct {
    char __size[4];
} pthread_mutexattr_t;
typedef struct {
    char __size[48];
} pthread_cond_t;
typedef struct {
    char __size[4];
} pthread_condattr_t;
typedef struct {
    char __size[56];
} pthread_rwlock_t;
typedef struct {
    char __size[8];
} pthread_rwlockattr_t;
typedef struct {
    char __size[32];
} pthread_barrier_t;
typedef struct {
    char __size[4];
} pthread_barrierattr_t;
typedef struct {
    double alpha;
    double beta;
    double gamma;
} SasaCoeffs;
typedef struct {
    double best_L;
    int last_improve_iter;
    int m;
    double sum_tau;
    double sum_r;
    double score;
} SasaState;
typedef struct {
    char name[8];
    double score;
    int latency_ms;
} RankingEntry;
typedef struct {
    int *adjacency;
    int adjacency_size;
    float *pheromones;
    int pheromone_size;
    float alpha;
    float beta;
    float evaporation;
    float Q;
    int num_ants;
    int is_initialized;
} AcoV1State;
typedef struct HeatmapRenderer HeatmapRenderer;
typedef struct {
    pthread_mutex_t lock;
    NodeData *start_node;
    NodeData *end_node;
    NodeData *hop_nodes;
    size_t hop_count;
    EdgeData *edges;
    size_t edge_count;
    int default_min_delay;
    int default_max_delay;
} HopMapManager;
typedef struct {
    int node_count;
    int min_hops;
    int max_hops;
    NodeData *nodes;
    int num_nodes;
    EdgeData *edges;
    int num_edges;
    int iteration;
    pthread_mutex_t lock;
    int random_best_nodes[1024];
    int random_best_length;
    int random_best_latency;
    AppConfig config;
    int brute_best_nodes[1024];
    int brute_best_length;
    int brute_best_latency;
    BruteForceState brute_state;
    int aco_best_nodes[1024];
    int aco_best_length;
    int aco_best_latency;
    AcoV1State aco_v1;
    SasaState aco_sasa;
    SasaState random_sasa;
    SasaState brute_sasa;
    SasaCoeffs sasa_coeffs;
    HopMapManager *hop_map_mgr;
} AntNetContext;



int pub_initialize(int node_count, int min_hops, int max_hops);
int pub_run_iteration(int context_id);
int pub_shutdown(int context_id);
int pub_get_best_path(int context_id, int *out_nodes, int max_size, int *out_path_len, int *out_total_latency);
int pub_run_all_solvers(int context_id, int *out_nodes_aco, int max_size_aco, int *out_len_aco, int *out_latency_aco, int *out_nodes_random, int max_size_random, int *out_len_random, int *out_latency_random, int *out_nodes_brute, int max_size_brute, int *out_len_brute, int *out_latency_brute);
int pub_init_from_config(const char *config_path);
int pub_get_config(int context_id, AppConfig *out);
int pub_get_pheromone_matrix(int context_id, float *out, int max_count);
int pub_render_heatmap_rgba(const float *pts_xy, const float *strength, int n, unsigned char *out_rgba, int width, int height);
int pub_renderer_async_init(int initial_width, int initial_height);
int pub_renderer_async_shutdown(void);
int pub_get_algo_ranking(int context_id, RankingEntry *out, int max_count);
int pub_set_sasa_params(int context_id, double alpha, double beta, double gamma);
int pub_get_sasa_params(int context_id, double *out_alpha, double *out_beta, double *out_gamma);
int pub_set_aco_params(int context_id, float alpha, float beta, float Q, float evaporation, int num_ants);
int pub_get_aco_params(int context_id, float *out_alpha, float *out_beta, float *out_Q, float *out_evaporation, int *out_num_ants);
int pub_update_topology(int context_id, const NodeData *nodes, int num_nodes, const EdgeData *edges, int num_edges);
void pub_config_set_defaults(AppConfig *cfg);
_Bool pub_config_load(AppConfig *cfg, const char *filepath);
_Bool pub_config_save(const AppConfig *cfg, const char *filepath);
'''